INSERT INTO KILLERS (id,name,file) VALUES (1, 'Trapper', 'Trapper.webp');
INSERT INTO KILLERS (id,name,file) VALUES (2, 'Wraith', 'Wraith.webp');
INSERT INTO KILLERS (id,name,file) VALUES (3, 'Hillybilly', 'Hillybilly.webp');
INSERT INTO KILLERS (id,name,file) VALUES (4, 'Nurse', 'Nurse.webp');
INSERT INTO KILLERS (id,name,file) VALUES (5, 'Huntress', 'Huntress.webp');
INSERT INTO KILLERS (id,name,file) VALUES (6, 'Shape', 'Shape.webp');
INSERT INTO KILLERS (id,name,file) VALUES (7, 'Hag', 'Hag.webp');
INSERT INTO KILLERS (id,name,file) VALUES (8, 'Doctor', 'Doctor.webp');
INSERT INTO KILLERS (id,name,file) VALUES (9, 'Cannibal', 'Cannibal.webp');
INSERT INTO KILLERS (id,name,file) VALUES (10, 'Nightmare', 'Nightmare.webp');
INSERT INTO KILLERS (id,name,file) VALUES (11, 'Pig', 'Pig.webp');
INSERT INTO KILLERS (id,name,file) VALUES (12, 'Clown', 'Clown.webp');
INSERT INTO KILLERS (id,name,file) VALUES (13, 'Spirit', 'Spirit.webp');
INSERT INTO KILLERS (id,name,file) VALUES (14, 'Legion', 'Legion.webp');
INSERT INTO KILLERS (id,name,file) VALUES (15, 'Plague', 'Plague.webp');
INSERT INTO KILLERS (id,name,file) VALUES (16, 'Ghost Face', 'Ghostface.webp');
INSERT INTO KILLERS (id,name,file) VALUES (17, 'Demogorgon', 'Demogorgon.webp');
INSERT INTO KILLERS (id,name,file) VALUES (18, 'Oni', 'Oni.webp');
INSERT INTO KILLERS (id,name,file) VALUES (19, 'Deathslinger', 'Deathslinger.webp');
INSERT INTO KILLERS (id,name,file) VALUES (20, 'Executioner', 'Executioner.webp');
INSERT INTO KILLERS (id,name,file) VALUES (21, 'Blight', 'Blight.webp');
INSERT INTO KILLERS (id,name,file) VALUES (22, 'Twins', 'Twins.webp');
INSERT INTO KILLERS (id,name,file) VALUES (23, 'Trickster', 'Trickster.webp');
INSERT INTO KILLERS (id,name,file) VALUES (24, 'Nemesis', 'Nemesis.webp');
INSERT INTO KILLERS (id,name,file) VALUES (25, 'Cenobite', 'Cenobite.webp');
INSERT INTO KILLERS (id,name,file) VALUES (26, 'Artist', 'Artist.webp');
INSERT INTO KILLERS (id,name,file) VALUES (27, 'Onryō', 'Onryō.webp');
INSERT INTO KILLERS (id,name,file) VALUES (28, 'Dredge', 'Dredge.webp');
INSERT INTO KILLERS (id,name,file) VALUES (29, 'Mastermind', 'Mastermind.webp');
INSERT INTO KILLERS (id,name,file) VALUES (30, 'Knight', 'Knight.webp');
INSERT INTO KILLERS (id,name,file) VALUES (31, 'Skull Merchant', 'Skullmerchant.webp');
INSERT INTO KILLERS (id,name,file) VALUES (32, 'Singularity', 'Singularity.webp');
INSERT INTO KILLERS (id,name,file) VALUES (33, 'Xenomorph', 'Xenomorph.webp');

INSERT INTO MAPS (id,name,file) VALUES (1, 'Coal Tower', 'CoalTower.webp');
INSERT INTO MAPS (id,name,file) VALUES (2, 'Groaning Storehouse', 'Storehouse.webp');
INSERT INTO MAPS (id,name,file) VALUES (3, 'Ironworks of Misery', 'Ironworks.webp');
INSERT INTO MAPS (id,name,file) VALUES (4, 'Shelter Woods', 'Shelterwoods.webp');
INSERT INTO MAPS (id,name,file) VALUES (5, 'Suffocation Pit', 'Suffocationpit.webp');
INSERT INTO MAPS (id,name,file) VALUES (6, 'Azarov''s Resting Place', 'Azarov.webp');
INSERT INTO MAPS (id,name,file) VALUES (7, 'Blood Lodge', 'Bloodlodge.webp');
INSERT INTO MAPS (id,name,file) VALUES (8, 'Gas Heaven', 'Gasheaven.webp');
INSERT INTO MAPS (id,name,file) VALUES (9, 'Wreckers'' Yard', 'Wreckers.webp');
INSERT INTO MAPS (id,name,file) VALUES (10, 'Wretched Shop', 'Wretchedshop.webp');
INSERT INTO MAPS (id,name,file) VALUES (11, 'Fractured Cowshed', 'Cowshed.webp');
INSERT INTO MAPS (id,name,file) VALUES (12, 'Rancid Abattoir', 'Rancidabattoir.webp');
INSERT INTO MAPS (id,name,file) VALUES (13, 'Rotten Fields', 'Rottenfields.webp');
INSERT INTO MAPS (id,name,file) VALUES (14, 'The Thompson House', 'Thompson.webp');
INSERT INTO MAPS (id,name,file) VALUES (15, 'Torment Creek', 'Torment.webp');
INSERT INTO MAPS (id,name,file) VALUES (16, 'Disturbed Ward', 'Disturbedward.webp');
INSERT INTO MAPS (id,name,file) VALUES (17, 'Father Campbell''s Chapel', 'Chapel.webp');
INSERT INTO MAPS (id,name,file) VALUES (18, 'Lampkin Lane', 'Lampkinlane.webp');
INSERT INTO MAPS (id,name,file) VALUES (19, 'The Pale Rose', 'Palerose.webp');
INSERT INTO MAPS (id,name,file) VALUES (20, 'Grim Pantry', 'Grimpantry.webp');
INSERT INTO MAPS (id,name,file) VALUES (21, 'Treatment Theatre', 'Treatment.webp');
INSERT INTO MAPS (id,name,file) VALUES (22, 'Mother''s Dwelling', 'Mothersdwelling.webp');
INSERT INTO MAPS (id,name,file) VALUES (23, 'The Temple of Purgation', 'Temple.webp');
INSERT INTO MAPS (id,name,file) VALUES (24, 'Badham Preschool I', 'BadhamI.webp');
INSERT INTO MAPS (id,name,file) VALUES (25, 'Badham Preschool II', 'BadhamII.webp');
INSERT INTO MAPS (id,name,file) VALUES (26, 'Badham Preschool III', 'BadhamIII.webp');
INSERT INTO MAPS (id,name,file) VALUES (27, 'Badham Preschool IV', 'BadhamIV.webp');
INSERT INTO MAPS (id,name,file) VALUES (28, 'Badham Preschool V', 'BadhamV.webp');
INSERT INTO MAPS (id,name,file) VALUES (29, 'The Game', 'Thegame.webp');
INSERT INTO MAPS (id,name,file) VALUES (30, 'Family Residence', 'Family.webp');
INSERT INTO MAPS (id,name,file) VALUES (31, 'Sanctum of Wrath', 'Sanctum.webp');
INSERT INTO MAPS (id,name,file) VALUES (32, 'Mount Ormond Resort', 'Ormond.webp');
INSERT INTO MAPS (id,name,file) VALUES (33, 'Dead Dawg Saloon', 'Saloon.webp');
INSERT INTO MAPS (id,name,file) VALUES (34, 'Midwich Elementary School', 'Midwich.webp');
INSERT INTO MAPS (id,name,file) VALUES (35, 'Raccoon City Police Station East Wing', 'RPDEast.webp');
INSERT INTO MAPS (id,name,file) VALUES (36, 'Raccoon City Police Station West Wing', 'RPDWest.webp');
INSERT INTO MAPS (id,name,file) VALUES (37, 'Eyrie of Crows', 'Eyrie.webp');
INSERT INTO MAPS (id,name,file) VALUES (38, 'Garden of Joy', 'Garden.webp');
INSERT INTO MAPS (id,name,file) VALUES (39, 'The Shattered Square', 'Shatteredsquare.webp');
INSERT INTO MAPS (id,name,file) VALUES (40, 'Toba Landing', 'Toba.webp');
INSERT INTO MAPS (id,name,file) VALUES (41, 'Nostromo Wreckage', 'Nostromo.webp');
