

INSERT INTO MAPS (id,name,file) VALUES (1, 'Coal Tower', 'CoalTower.webp');
INSERT INTO MAPS (id,name,file) VALUES (2, 'Groaning Storehouse', 'Storehouse.webp');
INSERT INTO MAPS (id,name,file) VALUES (3, 'Ironworks of Misery', 'Ironworks.webp');
INSERT INTO MAPS (id,name,file) VALUES (4, 'Shelter Woods', 'Shelterwoods.webp');
INSERT INTO MAPS (id,name,file) VALUES (5, 'Suffocation Pit', 'Suffocationpit.webp');
INSERT INTO MAPS (id,name,file) VALUES (6, 'Azarov''s Resting Place', 'Azarov.webp');
INSERT INTO MAPS (id,name,file) VALUES (7, 'Blood Lodge', 'Bloodlodge.webp');
INSERT INTO MAPS (id,name,file) VALUES (8, 'Gas Heaven', 'Gasheaven.webp');
INSERT INTO MAPS (id,name,file) VALUES (9, 'Wreckers'' Yard', 'Wreckers.webp');
INSERT INTO MAPS (id,name,file) VALUES (10, 'Wretched Shop', 'Wretchedshop.webp');
INSERT INTO MAPS (id,name,file) VALUES (11, 'Fractured Cowshed', 'Cowshed.webp');
INSERT INTO MAPS (id,name,file) VALUES (12, 'Rancid Abattoir', 'Rancidabattoir.webp');
INSERT INTO MAPS (id,name,file) VALUES (13, 'Rotten Fields', 'Rottenfields.webp');
INSERT INTO MAPS (id,name,file) VALUES (14, 'The Thompson House', 'Thompson.webp');
INSERT INTO MAPS (id,name,file) VALUES (15, 'Torment Creek', 'Torment.webp');
INSERT INTO MAPS (id,name,file) VALUES (16, 'Disturbed Ward', 'Disturbedward.webp');
INSERT INTO MAPS (id,name,file) VALUES (17, 'Father Campbell''s Chapel', 'Chapel.webp');
INSERT INTO MAPS (id,name,file) VALUES (18, 'Lampkin Lane', 'Lampkinlane.webp');
INSERT INTO MAPS (id,name,file) VALUES (19, 'The Pale Rose', 'Palerose.webp');
INSERT INTO MAPS (id,name,file) VALUES (20, 'Grim Pantry', 'Grimpantry.webp');
INSERT INTO MAPS (id,name,file) VALUES (21, 'Treatment Theatre', 'Treatment.webp');
INSERT INTO MAPS (id,name,file) VALUES (22, 'Mother''s Dwelling', 'Mothersdwelling.webp');
INSERT INTO MAPS (id,name,file) VALUES (23, 'The Temple of Purgation', 'Temple.webp');
INSERT INTO MAPS (id,name,file) VALUES (24, 'Badham Preschool I', 'BadhamI.webp');
INSERT INTO MAPS (id,name,file) VALUES (25, 'Badham Preschool II', 'BadhamII.webp');
INSERT INTO MAPS (id,name,file) VALUES (26, 'Badham Preschool III', 'BadhamIII.webp');
INSERT INTO MAPS (id,name,file) VALUES (27, 'Badham Preschool IV', 'BadhamIV.webp');
INSERT INTO MAPS (id,name,file) VALUES (28, 'Badham Preschool V', 'BadhamV.webp');
INSERT INTO MAPS (id,name,file) VALUES (29, 'The Game', 'Thegame.webp');
INSERT INTO MAPS (id,name,file) VALUES (30, 'Family Residence', 'Family.webp');
INSERT INTO MAPS (id,name,file) VALUES (31, 'Sanctum of Wrath', 'Sanctum.webp');
INSERT INTO MAPS (id,name,file) VALUES (32, 'Mount Ormond Resort', 'Ormond.webp');
INSERT INTO MAPS (id,name,file) VALUES (33, 'Dead Dawg Saloon', 'Saloon.webp');
INSERT INTO MAPS (id,name,file) VALUES (34, 'Midwich Elementary School', 'Midwich.webp');
INSERT INTO MAPS (id,name,file) VALUES (35, 'Raccoon City Police Station East Wing', 'RPDEast.webp');
INSERT INTO MAPS (id,name,file) VALUES (36, 'Raccoon City Police Station West Wing', 'RPDWest.webp');
INSERT INTO MAPS (id,name,file) VALUES (37, 'Eyrie of Crows', 'Eyrie.webp');
INSERT INTO MAPS (id,name,file) VALUES (38, 'Garden of Joy', 'Garden.webp');
INSERT INTO MAPS (id,name,file) VALUES (39, 'The Shattered Square', 'Shatteredsquare.webp');
INSERT INTO MAPS (id,name,file) VALUES (40, 'Toba Landing', 'Toba.webp');
INSERT INTO MAPS (id,name,file) VALUES (41, 'Nostromo Wreckage', 'Nostromo.webp');

INSERT INTO TEAMS (id,name) VALUES (1, 'Team 1');
INSERT INTO TEAMS (id,name) VALUES (2, 'Team 2');
INSERT INTO TEAMS (id,name) VALUES (3, 'Team 3');
INSERT INTO TEAMS (id,name) VALUES (4, 'Team 4');
INSERT INTO TEAMS (id,name) VALUES (5, 'Team 5');
INSERT INTO TEAMS (id,name) VALUES (6, 'Team 6');
INSERT INTO TEAMS (id,name) VALUES (7, 'Team 7');
INSERT INTO TEAMS (id,name) VALUES (8, 'Team 8');

